
sample:
  seed: 2024
  batch_size: 50
  num_mols: 100
  save_traj_prob: 0.02


data:
  protein_path: data/examples/peptide/3bik_A.pdb
  input_ligand: pepseq_DTVDFFEVFL  # define peptide: pepseq_{xxxxx}
  is_pep: True
  pocket_args:
    ref_ligand_path: data/examples/peptide/3bik_A_pocket_coord.sdf
    radius: 20
  pocmol_args:
    data_id: dockpep_3bik
    pdbid: 3bik


transforms:
  featurizer_pocket:
    center: [7.9130, -7.3910, -25.9240]  # space center for denosing



# The following defines docking task (Gaussian noise)

task:
  name: dock
  transform:
    name: dock
    settings:
      free: 1
      flexible: 0

noise:
  name: dock
  num_steps: 100
  prior: from_train
  level:
    name: advance
    min: 0.
    max: 1.
    step2level:
      scale_start: 0.99999
      scale_end: 0.00001
      width: 3