
sample:
  seed: 2024
  batch_size: 50
  num_mols: 100
  save_traj_prob: 0.02


data:
  protein_path: data/examples/peptide/3bik_A.pdb
  input_ligand: data/examples/peptide/P73.pdb
  pocket_args:
    radius: 20
  pocmol_args:
    data_id: dockpep_fix_some
    pdbid: 3bik


transforms:
  featurizer_pocket:
    center: [7.9130, -7.3910, -25.9240]  # space center for denosing



# The following defines docking task (Gaussian noise)
# with some atoms fixed (specified in task/transform/fix_some)

task:
  name: dock
  transform:
    name: dock
    settings:
      free: 1
      flexible: 0
    # specify fixed atoms/residues (index counts from 0) in the input_ligand file
    fix_some: # union of all the following:
      res_bb: [0, 1]  # the backbone atoms of the residue with indeces 0 and 1
      res_sc: [0]  #  the side-chain atoms of the residue with index 0
      atom: [73, 74, 75, 76, 77, 78]  # the atoms with indices 73-78. i.e., the benzene of Phe (resiude index 8) in this example

noise:
  name: dock
  num_steps: 100
  prior: from_train
  level:
    name: advance
    min: 0.
    max: 1.
    step2level:
      scale_start: 0.99999
      scale_end: 0.00001
      width: 3
  pre_process: fix_some