
sample:
  seed: 2024
  batch_size: 40
  num_mols: 100
  num_repeats: 1
  save_traj_prob: 0.02

transforms:
  featurizer_pocket:
    center: [-8.2570, 85.1810, 19.0500]  # space center
noise:
  name: dock
  num_steps: 100
  prior: from_train
  level:
    name: advance
    min: 0.
    max: 1
    step2level:
      scale_start: 0.99999
      scale_end: 0.00001
      width: 3

data:
  protein_path: data/examples/dock/8C7Y_TXV_protein.pdb
  # mol can be defined using smiles or sdf file
  # mol_path: CC(C)(C#N)c1cccc(C(=O)Nc2ccc(F)c(C(=O)c3c[nH]c4ncc(Cl)cc34)c2F)c1  # mol smiles
  mol_path: data/examples/dock/8C7Y_TXV_ligand_start_conf.sdf  # mol graph
  args:
    pocket_center: [-8.2570, 85.1810, 19.0500]  # for extracting pocket
    radius: 15
  
task:
  name: dock
  transform:
    name: dock
    settings:
      free: 0
      flexible: 1
