
sample:
  seed: 2023
  batch_size: 50
  num_mols: 100
  num_repeats: 1
  save_traj_prob: 0.0
transforms:
  featurizer_pocket:
    center: [7.9130, -7.3910, -25.9240]

noise:
  name: dock
  num_steps: 100
  prior: from_train
  level:
    name: advance
    min: 0.
    max: 1.
    step2level:
      scale_start: 0.99999
      scale_end: 0.00001
      width: 3

data:
  protein_path: data/examples/peptide/3bik_A.pdb
  ref_ligand_path: data/examples/peptide/pocket_center.sdf
  input_ligand: 'peptide_DTVDFFEVFL'
  pocket_args: 
    radius: 20
  pocmol_args:
    data_id: 3bik_dock
    pdbid: 3bik

task:
  name: dock
  transform:
    name: dock
    settings:
      free: 1
      flexible: 0
