
sample:
  seed: 2024
  batch_size: 100
  num_mols: 100
  num_repeats: 1
  save_traj_prob: 0.02

transforms:
  featurizer:
    mol_as_pocket_center: True  # ref mol center as the global center. can also use the commented line below.
  # featurizer_pocket:
  #   center: [-8.1603, 36.6972, 38.7714]
  variable_mol_size:  # variable mol size
    name: variable_mol_size
    num_atoms_distri:
      strategy: mol_atoms_based  # mol size from Normal(mean=28, std=2)
      mean:
        coef: 0
        bias: 28
      std:
        coef: 0
        bias: 2
      min: 5

noise:
  name: maskfill
  num_steps: 100
  ar_config:
    strategy: yiqijuan2
    r: 3
    threshold_node: 0.98
    threshold_pos: 0.91
    threshold_bond: 0.98
    max_ar_step: 10
    change_init_step: 1
  prior:
    part1: from_train
    part2: from_train
  level:
    part1:
      name: uniform
      min: 0.6
      max: 1.0
    part2:
      name: advance
      min: 0.0
      max: 1.0
      step2level:
        scale_start: 0.99999
        scale_end: 1.0e-05
        width: 3
data:
  protein_path: data/examples/smallmol/2ar9_A.pdb
  args:  # for function `process_raw`
    pocket_center: [-8.1603, 36.6972, 38.7714]
    radius: 15
  
task:
  name: sbdd
  transform:
    name: ar
    part1_pert: small
