
sample:
  seed: 2024
  batch_size: 50
model:
  checkpoint: data/trained_models/tuned_ranker/checkpoints/tuned_ranker.ckpt


# the following should not be changed for getting confidence

noise:
  name: dock
  num_steps: 1
  init_step: 0.01
  prior:
    pos: 
      name: allpos
      pos:
        name: gaussian_simple
        sigma_func: 'sqrt'
        sigma_max: 1.0
      translation:
        name: translation
        ve: False
        mean: 0
        std: 1
      rotation:
        name: rotation
        sigma_max: 0.0002
      torsional:
        name: torsional
        sigma_max: 0.2
        decouple: False
  level:
    name: advance
    min: 1.
    max: 1.
    step2level:
      scale_start: 0.99999
      scale_end: 0.00001
      width: 3


task:
  name: dock
  transform:
    name: dock
    settings:
      free: 1
      flexible: 0